FROM php:7.4-apache-bullseye AS php-apache

#COPY ./var/www/html/ /var/www/html

RUN cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/ && \
cp /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/ 