FROM openjdk:17 as builder1

FROM python:3.9
COPY --from=builder1 /usr/java/openjdk-17 /usr/java/openjdk-17
WORKDIR /

COPY requirements.txt ./requirements.txt
ENV JAVA_HOME /usr/java/openjdk-17
ENV PATH $JAVA_HOME/bin:$PATH

RUN pip install -r requirements.txt

CMD [ "python", "./flask_endpoints.py"]