version: '3'
services:
  learner:
    build: 
        context: ./src_learner
    image: src_learner:latest
    ports:
      - '5000:9007'
    command: sh -c 'python -m unittest discover /'
  php:
    build: 
        context: ./src_php
    image: src_php:latest
    ports:
      - '8089:80'
    working_dir: /
    command: sh -c "cd tests &&
        composer require --dev phpunit/phpunit ^9 &&
        /tests/vendor/bin/phpunit --bootstrap ./autoload.php tests"
  react:
    build: 
        context: ./src_react
    image: src_react:latest
    ports:
      - '3007:3000'
    working_dir: /app
    command: sh -c 'npm test'
