version: '3'
services:
  learner:
    build: 
        context: ./src_learner
    image: src_learner:latest
    working_dir: /src  
    ports:
      - '5000:9007'
  tests:
    build: 
        context: ./src_learner
    image: src_learner:latest
    depends_on:
      - learner
    working_dir: /src  
    volumes:
      - ./src_learner:/tests:cached
    command: sh -c "python -m unittest discover /src/tests"
     