name: CI tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    name: tests
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start php container
      working-directory: ./src/src_php/
      run: |
        docker build -f "dockerfile" . -t php
        
    - name: run php container
      working-directory: ./
      id: php
      run: |
        docker run --entrypoint sh -c "cd tests && composer require --dev phpunit/phpunit ^9 && /tests/vendor/bin/phpunit --bootstrap ./autoload.php tests" -t php

    - name: Stop containers
      working-directory: ./
      if: always()
      run: docker-compose -f "./src/docker-compose-tests.yml" down
